spring:
  application:
    name: @project.name@
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: info
