spring:
  application:
    name: @project.name@
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 300_000
      max-lifetime: 3_600_000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: info
