server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: @project.name@
  datasource:
    hikari:
      maximum-pool-size: 50
      connection-timeout: 300_000
      max-lifetime: 3_600_000
      data-source-properties:
        stringtype: unspecified
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  messages:
    basename: messages/errors

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: info

app:
  name: @project.name@
  description: @project.description@
  version: @project.version@
